apiVersion: hazelcast.com/v1alpha1
kind: HazelcastJetEnterprise
metadata:
  name: jet-enterprise-cluster
spec:
  cluster:
    memberCount: 2
  gracefulShutdown:
    enabled: true
    maxWaitSeconds: 600
  image:
    pullPolicy: IfNotPresent
    repository: hazelcast/hazelcast-jet-enterprise
    tag: "4.1"
  imagetag: hazelcast/hazelcast-jet-enterprise:4.1
  jet:
    javaOpts: null
    licenseKey: null
    yaml:
      hazelcast:
        cluster-name: jet
        management-center:
          enabled: ${hazelcast.mancenter.enabled}
          url: ${hazelcast.mancenter.url}
        network:
          join:
            kubernetes:
              enabled: true
              namespace: ${namespace}
              resolve-not-ready-addresses: true
              service-name: ${serviceName}
            multicast:
              enabled: false
          rest-api:
            enabled: true
            endpoint-groups:
              HEALTH_CHECK:
                enabled: true
      hazelcast-jet:
        edge-defaults:
          packet-size-limit: 16384
          queue-size: 1024
          receive-window-multiplier: 3
        instance:
          backup-count: 1
          flow-control-period: 100
          lossless-restart-enabled: false
          scale-up-delay-millis: 10000
        metrics:
          collection-interval-seconds: 5
          enabled: true
          jmx-enabled: true
          metrics-for-data-structures: false
          retention-seconds: 120
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 30
    path: /hazelcast/health/node-state
    periodSeconds: 10
    scheme: HTTP
    successThreshold: 1
    timeoutSeconds: 5
  managementcenter:
    enabled: true
    image:
      pullPolicy: IfNotPresent
      repository: hazelcast/hazelcast-jet-management-center
      tag: "4.1"
    javaOpts: null
    licenseKey: null
    livenessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    nodeSelector: {}
    readinessProbe:
      enabled: true
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    service:
      annotations: {}
      httpsPort: 443
      port: 8081
      type: LoadBalancer
    yaml:
      hazelcast-client:
        cluster-name: jet
        network:
          kubernetes:
            enabled: true
            namespace: ${namespace}
            resolve-not-ready-addresses: true
            service-name: ${serviceName}
  managementcenterimagetag: hazelcast/hazelcast-jet-management-center:4.1
  metrics:
    enabled: false
    service:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      port: 8080
      type: ClusterIP
  nodeSelector: {}
  rbac:
    create: true
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 30
    path: /hazelcast/health/ready
    periodSeconds: 10
    scheme: HTTP
    successThreshold: 1
    timeoutSeconds: 1
  securityContext:
    enabled: true
    fsGroup: 65534
    readOnlyRootFilesystem: true
    runAsGroup: 65534
    runAsUser: 65534
  service:
    clusterIP: None
    port: 5701
    type: ClusterIP
  serviceAccount:
    create: true
    name: null
