apiVersion: hazelcast.com/v1alpha1
kind: HazelcastJet
metadata:
  name: jet-cluster
spec:
  cluster:
    memberCount: 2
  jet:
    resources:
      requests:
        memory: 1024Mi
        cpu: 100m
      limits:
        memory: 1024Mi
  securityContext:
    runAsUser: ""
    runAsGroup: ""
    fsGroup: ""
  managementcenter:
    resources:
      requests:
        memory: 1024Mi
        cpu: 100m
      limits:
        memory: 1024Mi
